export default {
  products: [
    {
      _id: "1",
      name: "Floral Tops",
      category: "Shirts",
      image: "/images/product-1.jpg",
      price: 60,
      brand: "Zara",
      rating: 4.6,
      numReviews: 9,
      countInStock: 5,
    },

    {
      _id: "2",
      name: "BEIGE JOGGERS SMALL",
      category: "JOGGERS",
      image: "/images/product-2.jpg",
      price: 110,
      brand: "Zara",
      rating: 4.6,
      numReviews: 9,
      countInStock: 2,
    },

    {
      _id: "3",
      name: "Digital Floral Print Top",
      category: "Shirts",
      image: "/images/product-3.jpg",
      price: 30,
      brand: "Zara",
      rating: 4.6,
      numReviews: 9,
      countInStock: 5,
    },

    {
      _id: "4",
      name: "Hey Candy Zara Blazer Top",
      category: "Blazer",
      image: "/images/product-4.jpg",
      price: 90,
      brand: "Zara",
      rating: 4.6,
      numReviews: 9,
      countInStock: 5,
    },

    {
      _id: "5",
      name: "Zara Woman Floral Blazer",
      category: "Blazer",
      image: "/images/product-5.jpg",
      price: 78,
      brand: "Zara",
      rating: 4.6,
      numReviews: 9,
      countInStock: 5,
    },

    {
      _id: "6",
      name: "Authentic ZARA Blazer",
      category: "Blazer",
      image: "/images/product-6.jpg",
      price: 100,
      brand: "Zara",
      rating: 4.6,
      numReviews: 9,
      countInStock: 5,
    },

    {
      _id: "7",
      name: "ZARA JUMPSUIT",
      category: "Jumpsuit",
      image: "/images/product-7.jpg",
      price: 85,
      brand: "Zara",
      rating: 4.6,
      numReviews: 9,
      countInStock: 5,
    },

    {
      _id: "8",
      name: "Zara style jumpsuit",
      category: "Jumpsuit",
      image: "/images/product-8.jpg",
      price: 60,
      brand: "Zara",
      rating: 4.6,
      numReviews: 9,
      countInStock: 5,
    },

    {
      _id: "9",
      name: "Zara jumpsuit",
      category: "Jumpsuit",
      image: "/images/product-9.jpg",
      price: 95,
      brand: "Zara",
      rating: 4.6,
      numReviews: 9,
      countInStock: 5,
    },

    {
      _id: "10",
      name: "COD Zara Plain Jumpsuit Tie Business",
      category: "Jumpsuit",
      image: "/images/product-10.jpg",
      price: 76,
      brand: "Zara",
      rating: 4.6,
      numReviews: 9,
      countInStock: 5,
    },
  ],
};
